name: Run CI
on:
  pull_request:
    branches: master

jobs:
  CheckIfMatching:
    runs-on: ubuntu-latest
    if: ${{ github.head_ref != *Release }}
    steps:
      - name: Run PR CI
        run: echo "${{ github.event.number }}"
      - name: Run branch name
        run: echo "${{ github.head_ref }}"
      - name: conditon for brach
        run: 
         echo "Not release branch"
