name: Run CI
on:
  pull_request:
    branches: master

jobs:
  pull_request_ci:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Run PR CI
        run: echo "${{ github.event.number }}"
      - name: Run branch name
        run: echo "${{ github.even.head.ref }}"
