name: Reject non release PR
on:
  pull_request:
    branches: master

jobs:
  CheckIfMatching:
    runs-on: ubuntu-latest
    if: ${{ !endsWith(github.head_ref, 'Release') }}
    steps:
      - name: Pull number
        run: echo "${{ github.event.number }}"
      - name: Source branch
        run: echo "${{ github.head_ref }}"
      - name: conditon for brach
        run: | 
          curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/pradasi/Dashboard-api/pulls/${{ github.event.number }} -d '{"state":"close"}'
